name: Update the code restart the service

on:
  push:
    branches:
      - '*'

jobs:
  update-and-reload:
    runs-on: self-hosted
    steps:

    - name: Change the directory
      run: |
        cd /home/git-test/Yukta_frontend

    - name: pull the code
      run: |
        whoami
        pwd
        cd /home/git-test/Yukta_frontend
        pwd
        git checkout frontend 
    - name: Update the code
      run: |
        pwd
        cd /home/git-test/Yukta_frontend
        pwd
        git pull origin frontend
    - name: Reload the server
      run: |  
        pm2 reload frontend
        
